options:
  swift-release:
    default: distro
    type: string
    description: Swift PPA to configure (trunk, milestone, distro)
  # Ring configuration
  partition-power:
    default: 8
    type: int
    description: Partition power.
  replicas:
    default: 3
    type: int
    description: Minimum replicas.
  min-hours:
    default: 1
    type: int
    description: Minimum hours between balances
  # CA Cert info
  country:
    default: US
    type: string
    description: Country
  state:
    default: ST
    type: string
    description: State
  locale:
    default: City
    type: string
    description: Locale
  common-name:
    default: CN
    type: string
    description: Common Name
  bind-port:
    default: 8080
    type: int
    description: TCP port to listen on
