options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.
      .
      Supported Cloud Archive sources include:
        - cloud:precise-folsom,
        - cloud:precise-folsom/updates
        - cloud:precise-folsom/staging
        - cloud:precise-folsom/proposed
      .
      Note that updating this setting to a source that is known to
      provide a later version of OpenStack will trigger a software
      upgrade.
  region:
    default: RegionOne
    type: string
    description: OpenStack region that this swift-proxy supports.
  # Ring configuration
  partition-power:
    default: 8
    type: int
    description: Partition power.
  replicas:
    default: 3
    type: int
    description: Minimum replicas.
  min-hours:
    default: 1
    type: int
    description: Minimum hours between balances
  storage-zone-distribution:
    default: "service-unit"
    type: string
    description: |
      Storage zone distribution policy that the charm will use when
      configuring and initializing the storage ring upon new swift-storage
      relations (see README). Options include:
      .
        service-unit - Storage zones configured per swift-storage service unit.
        machine-unit - Storage zones configured per swift-storage machine-unit.
        manual - Storage zones configured manually per swift-storage service.
  # CA Cert info
  use-https:
    default: "yes"
    type: string
    description: Whether to listen on HTTPS
  country:
    default: US
    type: string
    description: Country
  state:
    default: ST
    type: string
    description: State
  locale:
    default: City
    type: string
    description: Locale
  common-name:
    default: CN
    type: string
    description: Common Name
  bind-port:
    default: 8080
    type: int
    description: TCP port to listen on
  workers:
    default: 0
    type: int
    description: Number of TCP workers to launch (0 for the number of system cores)
  operator-roles:
    default: "Member,Admin"
    type: string
    description: Comma-separated list of Swift operator roles.
  auth-type:
    default: tempauth
    type: string
    description: Auth method to use, tempauth or keystone
  # Manual Keystone configuration.
  keystone-auth-host:
    type: string
    description: Keystone authentication host
  keystone-auth-port:
    default: 35357
    type: int
    description: Keystone authentication port
  keystone-auth-protocol:
    default: http
    type: string
    description: Keystone authentication protocol
  keystone-admin-tenant-name:
    default: service
    type: string
    description: Keystone admin tenant name
  keystone-admin-user:
    type: string
    description: Keystone admin username
  keystone-admin-password:
    type: string
    description: Keystone admin password
