options:
  swift-release:
    default: distro
    type: string
    description: Swift PPA to configure (trunk, milestone, distro)
  # Ring configuration
  partition-power:
    default: 8
    type: int
    description: Partition power.
  replicas:
    default: 3
    type: int
    description: Minimum replicas.
  min-hours:
    default: 1
    type: int
    description: Minimum hours between balances
  # CA Cert info
  country:
    default: US
    type: string
    description: Country
  state:
    default: ST
    type: string
    description: State
  locale:
    default: City
    type: string
    description: Locale
  common-name:
    default: CN
    type: string
    description: Common Name
  bind-port:
    default: 8080
    type: int
    description: TCP port to listen on
  auth-type:
    default: tempauth
    type: string
    description: Auth method to use, tempauth or keystone
  keystone-auth-host:
    type: string
    description: Keystone authentication host
  keystone-auth-port:
    default: 35357
    type: int
    description: Keystone authentication port
  keystone-auth-protocol:
    default: http
    type: string
    description: Keystone authentication protocol
  keystone-admin-tenant-name:
    default: service
    type: string
    description: Keystone admin tenant name
  keystone-admin-user:
    type: string
    description: Keystone admin username
  keystone-admin-password:
    type: string
    description: Keystone admin password
  swift-series:
    type: string
    description: Swift major series being installed (via swift-release)
    default: 1.4
